project_id = "bztievslvjgppilznaon"

[functions.briefcase-chat]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-legal-form]
verify_jwt = true

[functions.assistant-chat]
verify_jwt = false
